[package]
name = "notion-md-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = { version = "6.0.1", features = ["serde"] }
log = "0.4.20"
